
font_family Courier Prime SemiBold
font_size 12.0

background_opacity 0.3

window_padding_width 0

scrollback_lines 1024

cursor_shape underline
cursor_blink_interval 0.5

enable_audio_bell no

confirm_os_window_close 0

foreground #eae5e1
background #0c0c09

selection_foreground #0c0c09
selection_background #eae5e1

color0  #8d9185
color1  #b1b69d
color2  #cab38e
color3  #d4c8b2
color4  #d1c3b4
color5  #d3c7ba
color6  #ded6ce
color7  #eae5e1

color8  #b9b6af
color9  #b1b69d
color10 #cab38e
color11 #d4c8b2
color12 #d1c3b4
color13 #d3c7ba
color14 #ded6ce
color15 #eae5e1

tab_bar_min_tabs 2
active_tab_foreground   #0c0c09
active_tab_background   #d4c8b2
inactive_tab_foreground #b9b6af
inactive_tab_background #0c0c09

map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
