background {
    monitor =
    path = /home/pandeyps/dotfiles/wallpapers/sunset-lake.png
    blur_passes = 3
    blur_size = 6
}

label {
    monitor =
    text = $TIME
    font_family = Courier Prime
    font_size = 96
    color = rgba(212, 200, 178, 1.0)
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    font_family = Courier Prime
    font_size = 22
    color = rgba(234, 229, 225, 0.8)
    position = 0, 60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 48, 48
    outline_thickness = 5
    rounding = 24
    outer_color = rgba(fb4934ff)
    inner_color = rgba(00000000)
    check_color = rgba(9e948966)
    fail_color = rgba(fb4934ff)
    font_color = rgb(234, 229, 225)
    fade_on_empty = false
    font_family = Courier Prime
    placeholder_text =
    dots_spacing = 0.3
    position = 120, 80
    halign = left
    valign = bottom
}
